
      real*4    
     *          power1,power2
     *         ,power,power_perc
     *         ,power_ric,power2_ric
     *         ,power_ric_perc,power2_ric_perc
     *         ,power_perc_var
     *         ,power_perc_rev
     *         ,nom_pow_der

      common/argo_reale_ris/
     *            power1(MAX_UNIT),power2(MAX_UNIT)
     *           ,power(MAX_UNIT),power_perc(MAX_UNIT)
     *           ,power_ric(MAX_UNIT),power2_ric(MAX_UNIT)
     *           ,power_ric_perc(MAX_UNIT),power2_ric_perc(MAX_UNIT)
c-bp05
     *           ,power_perc_var(MAX_UNIT)
     *           ,power_perc_rev(MAX_UNIT)
     *           ,nom_pow_der(MAX_UNIT)
c-bp05-end