*----------------------------------------------------------------------
c parametri e common per l'utilizzo della Redlich-Kwong
*----------------------------------------------------------------------
c
      INTEGER*4  FLAG_CONVERGENZA
      
      
      
     
C   =1: SIRE2000   INPUT_ENERGIA+OUTPUT_ENERGIA
C   =2: NUOVOSIRE  INPUT_VOLUME+OUTPUT_VOLUME
C   =3:            INPUT_VOLUME+OUTPUT_ENERGIA
C   =4:            INPUT_ENERGIA+OUTPUT_VOLUME



common/FLAG_CONVER/FLAG_CONVERGENZA
